// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/sign-on": {
    params: {};
  };
  "/:status/:param": {
    params: {
      "status": string;
      "param": string;
    };
  };
  "/dashboard": {
    params: {};
  };
  "/forms": {
    params: {};
  };
  "/forms/create": {
    params: {};
  };
  "/forms/:formId": {
    params: {
      "formId": string;
    };
  };
  "/form-submissions": {
    params: {};
  };
  "/form-submissions/:submissionId": {
    params: {
      "submissionId": string;
    };
  };
  "/forms/:formId/submit": {
    params: {
      "formId": string;
    };
  };
  "/forms/:formId/submissions": {
    params: {
      "formId": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/sign-on" | "/:status/:param" | "/dashboard" | "/forms" | "/forms/create" | "/forms/:formId" | "/form-submissions" | "/form-submissions/:submissionId" | "/forms/:formId/submit" | "/forms/:formId/submissions";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/signon.tsx": {
    id: "routes/signon";
    page: "/sign-on";
  };
  "routes/oauth-callback.tsx": {
    id: "routes/oauth-callback";
    page: "/:status/:param";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "routes/forms/index.tsx": {
    id: "routes/forms/index";
    page: "/forms";
  };
  "routes/forms/create.tsx": {
    id: "routes/forms/create";
    page: "/forms/create";
  };
  "routes/forms/detail.tsx": {
    id: "routes/forms/detail";
    page: "/forms/:formId";
  };
  "routes/form-submissions/index.tsx": {
    id: "routes/form-submissions/index";
    page: "/form-submissions";
  };
  "routes/form-submissions/detail.tsx": {
    id: "routes/form-submissions/detail";
    page: "/form-submissions/:submissionId";
  };
  "routes/forms/submit.tsx": {
    id: "routes/forms/submit";
    page: "/forms/:formId/submit";
  };
  "routes/forms/submissions.tsx": {
    id: "routes/forms/submissions";
    page: "/forms/:formId/submissions";
  };
};